# NOTE : conf in this file are not cumulative and cancel any option passed to traefik at launch with command in docker compose file

api:
  dashboard: true
  debug: false
  insecure: true

log:
  level: "DEBUG"


entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    # If set to false, containers that don't have a traefik.enable=true label will be ignored from the resulting routing configuration
    #exposedByDefault: false
  file:
    filename: /etc/traefik/services.yml
